name: ale_favorite_strings
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Riverpod, the only dependency really needed
  # https://pub.dev/packages/flutter_riverpod
  flutter_riverpod: ^2.3.4
  # Needed by Freezed
  # https://pub.dev/packages/json_annotation
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  # Needed by Freezed
  # https://pub.dev/packages/build_runner
  build_runner: ^2.3.3
  # Almost immutable classes, mainly for data models
  # https://pub.dev/packages/freezed
  freezed: ^2.3.2

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
